services:
  gaps-scraper:
    restart: always
    build: .
    image: ghrc.io/andrecostaaa/gaps-scraper
    container_name: gaps-scraper
    volumes:
      - ./data:/app/data
    env_file:
      - .env
